version: '3.0'
services:
  mysql:
    container_name: mysql
    build:
      context: .
      dockerfile: Dockerfile-mysql
    env_file: ./.env
    image: mysql:8
    ports:
      - $MYSQL_HOST_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - /docker/emps/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE

    command: --explicit_defaults_for_timestamp

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile-app
    env_file: ./.env
    image: app:1.0.0
    links:
      - mysql:mysql
    ports:
      - $SPRING_HOST_PORT:$SPRING_DOCKER_PORT
    depends_on:
      - "mysql"
    environment:
      DB_HOST: mysql
